### ISSUE TITLE
Enhancement - Resilient Illusion

### ISSUE THREAD

**Issue by Bakaten** [Stari0n/MagicTime#2]
Will it be possible to add Resilient Illusion into the arcane discoveries?
[https://www.d20pfsrd.com/classes/core-classes/wizard/arcane-discoveries/arcane-discoveries-paizo/resilient-illusions/](url)
Thank you.

**Comment by kreaddy** [comment]
Unlikely. It's very niche because it's only relevant to shadow spells in the context of the game. I'd be more inclined to change the Powerful Shadows mythic ability to make it suck less though it isn't a priority either.

**Comment by Bakaten** [comment]
No problems. Looking forward to other future contents from this mod. 
Thank you for your hard works :)
