### ISSUE TITLE
Blood Arcanist can't level up Arcane Bloodline

### ISSUE THREAD

**Issue by Mister-Moth** [Stari0n/MagicTime#4]
This is going to sound like a tongue twister: My blood arcanist with the arcane bloodline can't level up past level nine. The "New Arcana" feature doesn't show any spell options, so it's impossible to move past that selection screen and complete the leveling process. Obviously, "new arcana" doesn't add much to a class that can learn spells from scrolls, but it looks like it needs to be fixed anyway.

In case it matters, I was using a lich-merged spellbook and the standard mods like Respec and TabletopTweaks.

**Comment by kreaddy** [comment]
Should be fixed now.

It had nothing to do with merged spellbook, it was just me being a dum-dum.
