### ISSUE TITLE
Causes infinite loading on 1.2 Beta

### ISSUE THREAD

**Issue by Woffingshire** [Stari0n/MagicTime#7]
Something in this mod, and it is this mod, causes the game to be stuck on the initial loading screen forever while on the 1.2 beta. Inevitably whatever changed in the update will also prevent the game from loading with this mod on actual 1.2

**Comment by kreaddy** [comment]
Not surprised in the least. I can't do anything about it because I don't have beta access (Gog user). I'll fix things for the actual 1.2 release.
